version: "3.8"
services:
  dcs-postgres:
    image: postgres:15.3-alpine
    container_name: outlive-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: root
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: outlive-pgadmin
    restart: always
    depends_on:
      - dcs-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: rafaelmchaves@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - '8081:80'
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
